name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check backend || true
      - name: Run backend tests
        run: |
          pip install pytest pytest-cov
          pytest backend -q || true

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend dependencies
        working-directory: frontend/vite-project
        run: |
          npm ci
      - name: Build frontend
        working-directory: frontend/vite-project
        run: |
          npm run build

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image (no push)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: backend/Dockerfile
          push: false
          tags: twinecapital/backend:ci-latest
